export const DISPLAY_BICYCLE_ROAD = 'DISPLAY_BICYCLE_ROAD'
export const DISPLAY_FACILITY = 'DISPLAY_FACILITY'
export const DISPLAY_INFO = 'DISPLAY_INFO'

export const DISPLAY_AIRPUMP = 'DISPLAY_AIRPUMP'
export const DISPLAY_PARKING = 'DISPLAY_PARKING'
export const DISPLAY_REPAIR = 'DISPLAY_REPAIR'
export const DISPLAY_RENTAL = 'DISPLAY_RENTAL'

export const SELECT_MARKER = 'SELECT_MARKER'
export const DISPLAY_AIR = 'DISPLAY_AIR'