export const DISPLAY_OLD_REPORT = "DISPLAY_OLD_REPORT";
export const DISPLAY_NEW_REPORT = "DISPLAY_NEW_REPORT";
export const DISPLAY_REPORT_DETAIL = "DISPLAY_REPORT_DETAIL";

export const REPORT_MODE = "REPORT_MODE";
export const SET_LATLNG = "SET_LATLNG";
export const SET_DETAILADDR = "SET_DETAILADDR";

export const ALERT_MESSAGE = "ALERT_MESSAGE";
